// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzc1LHq-XZ1u7CJrDk41mZRO1bZAQYAFQ',
    appId: '1:997871305049:web:f7cb70eaa42e85f9e5cc48',
    messagingSenderId: '997871305049',
    projectId: 'outsource-mate-f4c50',
    authDomain: 'outsource-mate-f4c50.firebaseapp.com',
    storageBucket: 'outsource-mate-f4c50.appspot.com',
    measurementId: 'G-QXW8SYMC6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjxfkeNhSHCvfG221qBH4PcvS_1ZwikI',
    appId: '1:997871305049:android:a5b17e78198ccea6e5cc48',
    messagingSenderId: '997871305049',
    projectId: 'outsource-mate-f4c50',
    storageBucket: 'outsource-mate-f4c50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oXm1YCy9tizFiigPby2k_itsgKo8JqQ',
    appId: '1:997871305049:ios:c3b9fa1eccc61562e5cc48',
    messagingSenderId: '997871305049',
    projectId: 'outsource-mate-f4c50',
    storageBucket: 'outsource-mate-f4c50.appspot.com',
    iosBundleId: 'com.shopifyistic.outsourceMate',
  );
}
